language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t hoesslj/react-test -f ./client/Dockerfile.dev ./client/

script:
    - docker info
    #- docker run -e CI=true hoesslj/react-test npm test

after_success: # To build production version 
    - docker build -t hoesslj/multi-client ./client
    - docker build -t hoesslj/multi-server ./server
    - docker build -t hoesslj/multi-nginx ./nginx
    - docker build -t hoesslj/multi-worker ./worker
    # Take those images and push them to docker hub
    # First, log in to the docker CLI
    - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin
    #- docker -login -u $DOCKER_ID -p $DOCKER_PW  
    - echo "Output of login attempt returned $?"
    # Then push the different images
    - docker push hoesslj/multi-client
    - docker push hoesslj/multi-server
    - docker push hoesslj/multi-nginx
    - docker push hoesslj/multi-worker
deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: multiDocker-env-1
    bucket_name: elasticbeanstalk-us-east-2-077844377417
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

